### ISSUE TITLE
Splashscreens

### ISSUE THREAD

**Issue by Jensovic** [webprofusion/apetools#1]
Hi there,

it seems like in your latest release the splashscreens are the same images as the logos. Splashscreen upload seems to be ignored.

**Comment by webprofusion-chrisc** [comment]
Thanks! That's fixed now.

**Comment by kidequinox** [comment]
I'm having same issue on the website.

**Comment by Jensovic** [comment]
Great! I'll test it...
Hmm, but still not working. Is it already implemented?
It still pulls the logo image. If only splash is inserted, it is used, but the screens are far off.

**Comment by webprofusion-chrisc** [comment]
Interesting, could be the browser cache needs cleared? I'll check again that it published ok.

**Comment by webprofusion-chrisc** [comment]
Hi, I can confirm when I use the current live version with two different images (one for icon one for splash) that they now get processed independently. When you say 'the screens are far off' can you describe what you mean? You're downloading the zip file?

**Comment by Jensovic** [comment]
Hi, currently the website seems down. With "far off" I meant that the splash images did not scale properly. In my opinion the icon size was pulled. I checked on two different computers. Don't think the cache can be involved there. I hope you can fix the problem. I was using your tool for my new app. Lets hope that you can get it back online soon :)

**Comment by webprofusion-chrisc** [comment]
Thanks, that's back up now - it's also on a server where an SSL cert tool get tested so sometimes we end up breaking the certificates.

Regarding scale: Icons should be square and the resize will just fit the image to that size (48x48 etc), this can affect aspect ratio if your original image is rectangular. Splashscreens should maintain their aspect ratio and should ideally use a 'best fit' to fit in the allocated size, I notice sometime this is not working so I'll file a new issue for that.

**Comment by Jensovic** [comment]
Glad you're back again!! Thank you for the good work!
